### ISSUE TITLE
Hi I am using coordinates in decimal for calculating the distance from animal movement data. But there is error "Warning message: In proj4string(xy) : CRS object has comment, which is lost in output"

### ISSUE THREAD

**Issue by rainforest-stat** [earthlab/cft#141]

**Comment by WilliamsTravis** [comment]
Hi there, this warning might have something to do with a recent change in the PROJ package. Could you send the command you used along with the CFT version and your OS?

**Comment by DrWKID** [comment]
@rainforest-stat - did you resolve this issue with a an update to the PROJ package?

**Comment by ttuff** [comment]
I'm sorry you had this trouble. This error was cause because one of the package we built cft around has gone through a series of changes that broke our spatial projection architecture. We have rewritten this package to use more modern infrastructure and you should find it to be much more stable and geographically sound.
