### ISSUE TITLE
cftdata() returning NA for all values (temp, precip, rh) in version 4.1

### ISSUE THREAD

**Issue by Janelle88** [earthlab/cft#148]
When running the cftdata() function, a warning pops up saying:
`no non-missing arguments to min; returning Inf no non-missing arguments to max; returning -Inf ` 

and the proceeding dataframe after running cft_df() returns all NA values. When I stop it from running all the way through, another error:

`Error in try(.Call(R_nc_inq_grp_parent, ncid), silent = TRUE) : NetCDF: No group found.` 

comes up when running the function in R 4.1. I do not get that specific error when running and stopping R in version 4.0.5. Looking into the code, it must be an issue with the NetCDF package, specifically the `grp.inq.nc` function that is a part of `read.nc` but I am unsure of any work arounds for this issue.

**Comment by acrunyon** [comment]
I am having this same issue, but without the same errors. When I run cftdata() for particular GCMs (eg, GFDL-ESM2G and GFDL-ESM2M) the data returned are NA values, resulting in NaNs when running cft_df(). For other GCMs (eg CCSM4 and bcc-csm1-1-m), values are _almost_ always returned. I have tried this using R 4.0.5 and R 4.1.1. I am using the most recent release of the package, 0.4.0.

**Comment by ttuff** [comment]
Thanks for your comments. The package is suffering some problems that are taking some time to repair. I'm working on those repairs now but they are taking a few days longer than expected. I should have a new version pushed with fixes for this problem and others.

**Comment by ttuff** [comment]
Expect fixes by mid-week next week.

**Comment by acrunyon** [comment]
Excellent and thank you for the update

________________________________
From: Ty Tuff ***@***.***>
Sent: Thursday, September 16, 2021 17:12
To: earthlab/cft ***@***.***>
Cc: Runyon, Amber N ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [earthlab/cft] cftdata() returning NA for all values (temp, precip, rh) in version 4.1 (#148)




 This email has been received from outside of DOI - Use caution before clicking on links, opening attachments, or responding.



Expect fixes by mid-weed next week.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fearthlab%2Fcft%2Fissues%2F148%23issuecomment-921323966&data=04%7C01%7Camber_runyon%40nps.gov%7Cd20b7730318d4132381e08d9796771d4%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637674307466204173%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nX488NGVVa%2BrQBJTKq4SmWQJneOjND24l8EFDDJAUOU%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABIODWWTIMU4D5HHBI3VPHLUCJ2UVANCNFSM5CM3HIAQ&data=04%7C01%7Camber_runyon%40nps.gov%7Cd20b7730318d4132381e08d9796771d4%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637674307466214126%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ltc%2BpsYcTYsTxCbzPMJ4DXeogdFopM2OwomOe3dTPB8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Camber_runyon%40nps.gov%7Cd20b7730318d4132381e08d9796771d4%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637674307466214126%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2SJHYKIzR7%2F9PQaigrHlNiXkXmyZ2Mub61XTVmIZTH8%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Camber_runyon%40nps.gov%7Cd20b7730318d4132381e08d9796771d4%7C0693b5ba4b184d7b9341f32f400a5494%7C0%7C0%7C637674307466224079%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=iZ0%2B1cxr7uEn47RQqyyo4DPlwkXBXQxoOD8TINOsLw8%3D&reserved=0>.

**Comment by acrunyon** [comment]
Hi Ty, following up to see if there are updates on when the package may be working again?

**Comment by ttuff** [comment]
Thank you for following up! I am very, very close to done with the fixes. I thought I would be done today, but I’ve had a few distractions that have set me back a bit. It’s my top priority for the next few days and I think you can reasonably expect a release by the end of Friday. Sorry for the delay but I think you’ll be happy with the changes. 

Cheers,
Ty

**Comment by ttuff** [comment]
cftdata has been deprecated because the the demise of gdal. Please see our replacement function https://github.com/earthlab/cft/blob/main/vignettes/firehose.md and let us know if you have any problems.
