### ISSUE TITLE
Commented out test?

### ISSUE THREAD

**Issue by mbjoseph** [earthlab/cft#77]
@WilliamsTravis we have a commented out a unit test: https://github.com/earthlab/cst/blob/master/tests/testthat/test-shapefile.R#L31-L35

Is this test broken after some other changes? 

We should avoid having commented out code - it's confusing and adds to the maintenance burden. Also, if a test stops working, it's important that we either fix the code so that the test passes, or fix the test if necessary (e.g., if the test was wrong in some way).

**Comment by WilliamsTravis** [comment]
Right, no problem. I should've made an issue instead. This test was failing on my windows build test because of some difficulties with the sf package (do we use the sf package anywhere else?) and is already covered in two previous tests. All get_shapefile calls are ultimately reading local files even if a remote url is fed in, since we are saving to a file first. It is actually possible to read directly from a remote source with readOGR, but it's useful to store locally to improve future run times.
